import "../styles/globals.css";
import "ress";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js with Framer Motion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="bg-primary-black overflow-hidden">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
